# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('lib', __dir__)
require 'open-uri'
require 'yaml'
require 'muren/contrib/version'

desc 'run specs'
task(:spec) { ruby '-S rspec' }
task(test: :spec)
task(default: :spec)

namespace :doc do
  task :readmes do
    Dir.glob 'lib/muren/*.rb' do |file|
      puts "Trying file... #{file}"
      excluded_files = %w[lib/muren/contrib.rb lib/muren/decompile.rb]
      next if excluded_files.include?(file)

      doc  = File.read(file)[/^module Muren(\n)+(  #[^\n]*\n)*/m].scan(/^ *#(?!#) ?(.*)\n/).join("\n")
      file = "doc/#{file[4..-4].tr('/_', '-')}.rdoc"
      Dir.mkdir 'doc' unless File.directory? 'doc'
      puts "writing #{file}"
      File.open(file, 'w') { |f| f << doc }
    end
  end

  task :index do
    doc = File.read('README.md')
    file = 'doc/muren-contrib-readme.md'
    Dir.mkdir 'doc' unless File.directory? 'doc'
    puts "writing #{file}"
    File.open(file, 'w') { |f| f << doc }
  end

  task all: %i[readmes index]
end

desc 'generate documentation'
task doc: 'doc:all'

desc 'generate gemspec'
task 'muren-contrib.gemspec' do
  content = File.read 'muren-contrib.gemspec'

  fields = {
    authors: `git shortlog -sn`.scan(/[^\d\s].*/),
    email: `git shortlog -sne`.scan(/[^<]+@[^>]+/),
    files: `git ls-files`.split("\n").grep_v(/^(\.|Gemfile)/)
  }

  fields.each do |field, values|
    updated = "  s.#{field} = ["
    updated << values.map { |v| "\n    %p" % v }.join(',')
    updated << "\n  ]"
    content.sub!(/  s\.#{field} = \[\n(    .*\n)*  \]/, updated)
  end

  File.open('muren-contrib.gemspec', 'w') { |f| f << content }
end

task gemspec: 'muren-contrib.gemspec'

task release: :gemspec do
  sh <<-SH
    rm -Rf muren-contrib*.gem &&
    gem build muren-contrib.gemspec &&
    gem install muren-contrib*.gem --local &&
    gem push muren-contrib*.gem  &&
    git commit --allow-empty -a -m '#{Muren::Contrib::VERSION} release'  &&
    git tag -s v#{Muren::Contrib::VERSION} -m '#{Muren::Contrib::VERSION} release'  &&
    git push && (git push origin main || true) &&
    git push --tags && (git push origin --tags || true)
  SH
end
